import {
  DEFAULT_WORKFLOW_LIMITS,
  WEBSITE_TO_VIDEO_SKIPPED_STEPS,
  type WorkflowSkippedStep,
} from "./website-to-video-workflow";
import { normalizeProjectPath } from "./project-paths";

const ENCODER = new TextEncoder();

export interface CaptureScreenshot {
  path: string;
  width?: number;
  height?: number;
}

export interface CaptureAsset {
  path: string;
  contentType?: string;
  size?: number;
}

export interface RawCaptureSummary {
  url: string;
  title?: string;
  description?: string;
  text?: string;
  screenshots?: Array<CaptureScreenshot>;
  assets?: Array<CaptureAsset>;
}

export interface NormalizedCaptureSummary {
  url: string;
  title: string;
  description: string;
  text: string;
  screenshots: Array<CaptureScreenshot>;
  assets: Array<CaptureAsset>;
}

export interface WorkflowWorkspaceFile {
  path: string;
  content: string;
  contentType: string;
}

export interface ComposedWebsiteToVideoArtifacts {
  files: Array<WorkflowWorkspaceFile>;
  skippedSteps: Array<WorkflowSkippedStep>;
  warnings: Array<string>;
}

export function normalizeCaptureSummary(input: RawCaptureSummary): NormalizedCaptureSummary {
  const url = new URL(input.url).href;
  return {
    url,
    title: compact(input.title || hostnameTitle(url), 120),
    description: compact(input.description || "Website capture summary", 500),
    text: compact(input.text || "", 4_000),
    screenshots: (input.screenshots ?? []).slice(0, DEFAULT_WORKFLOW_LIMITS.maxScreenshots),
    assets: (input.assets ?? []).slice(0, 24),
  };
}

export function composeWebsiteToVideoArtifacts(input: {
  runId: string;
  sourceUrl: string;
  durationSec?: number;
  capture: NormalizedCaptureSummary;
  skillRevision?: string;
  skillContext?: string;
}): ComposedWebsiteToVideoArtifacts {
  const durationSec = clampDuration(input.durationSec);
  const title = input.capture.title;
  const sourceUrl = new URL(input.sourceUrl).href;
  const description = input.capture.description;
  const text = input.capture.text || "No page text was extracted by the first-pass capture.";

  const design = `# Website To Video Design

Source: ${sourceUrl}
Skill: /website-to-video
Skill revision: ${input.skillRevision || "unknown"}
Duration: ${durationSec}s

## Visual Direction

Create a concise website tour for ${title}. Use the captured site's own messaging, visual hierarchy, and product promise as the basis for the animation.

## Page Summary

${description}

## Extracted Signals

${text}

## Skill Context

${input.skillContext ? compact(input.skillContext, 1_200) : "Synced /website-to-video guidance was not available."}
`;

  const script = `# Script

0.0-2.0s: Introduce ${title} and establish the main promise.
2.0-${Math.max(4, durationSec - 2).toFixed(1)}s: Move through the strongest captured proof points and visual sections.
${Math.max(4, durationSec - 2).toFixed(1)}-${durationSec.toFixed(1)}s: Resolve on a clear product takeaway and call to action.

Voiceover: skipped in this first runner pass.
`;

  const storyboard = `# Storyboard

## Scene 1
Hero framing from ${sourceUrl}; emphasize the page title and primary value proposition.

## Scene 2
Feature/proof sequence using captured page language and assets.

## Scene 3
End card with concise CTA and brand-color accents inferred from the page.

Snapshots: generated by the workflow validation phase when the container is available.
`;

  const html = buildCompositionHtml({ title, description, durationSec, sourceUrl });

  return {
    files: [
      markdownFile("DESIGN.md", design),
      markdownFile("SCRIPT.md", script),
      markdownFile("STORYBOARD.md", storyboard),
      {
        path: "index.html",
        content: html,
        contentType: "text/html; charset=utf-8",
      },
    ],
    skippedSteps: WEBSITE_TO_VIDEO_SKIPPED_STEPS,
    warnings: [],
  };
}

export function validateWorkspaceFiles(
  files: Array<WorkflowWorkspaceFile>,
  limits: { maxFiles: number; maxArtifactBytes: number } = DEFAULT_WORKFLOW_LIMITS,
): { ok: true } | { ok: false; reason: string } {
  if (files.length > limits.maxFiles) {
    return { ok: false, reason: `too many files; maximum is ${limits.maxFiles}` };
  }
  const required = new Set(["DESIGN.md", "SCRIPT.md", "STORYBOARD.md", "index.html"]);
  let totalBytes = 0;
  for (const file of files) {
    let normalized: string;
    try {
      normalized = normalizeProjectPath(file.path);
    } catch {
      return { ok: false, reason: `invalid path: ${file.path}` };
    }
    required.delete(normalized);
    totalBytes += ENCODER.encode(file.content).byteLength;
    if (totalBytes > limits.maxArtifactBytes) {
      return { ok: false, reason: `artifact bytes exceed ${limits.maxArtifactBytes}` };
    }
  }
  if (required.size) {
    return { ok: false, reason: `missing required file: ${Array.from(required).join(", ")}` };
  }
  return { ok: true };
}

function markdownFile(path: string, content: string): WorkflowWorkspaceFile {
  return { path, content, contentType: "text/markdown; charset=utf-8" };
}

function buildCompositionHtml(input: {
  title: string;
  description: string;
  durationSec: number;
  sourceUrl: string;
}): string {
  const safeTitle = escapeHtml(input.title);
  const safeDescription = escapeHtml(input.description);
  const safeUrl = escapeHtml(input.sourceUrl);
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${safeTitle} Website Video</title>
  <style>
    html, body { margin: 0; width: 100%; height: 100%; background: #101820; color: white; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
    .frame { width: 1920px; height: 1080px; box-sizing: border-box; padding: 112px; display: grid; align-content: center; gap: 34px; background: linear-gradient(135deg, #101820 0%, #173b44 52%, #f26f3d 100%); }
    .eyebrow { font-size: 34px; letter-spacing: 0; text-transform: uppercase; opacity: .82; }
    h1 { margin: 0; max-width: 1280px; font-size: 122px; line-height: .96; letter-spacing: 0; }
    p { margin: 0; max-width: 1120px; font-size: 42px; line-height: 1.18; color: rgba(255,255,255,.88); }
    .bar { width: 720px; height: 18px; background: rgba(255,255,255,.9); transform-origin: left; animation: grow ${input.durationSec}s linear forwards; }
    .source { font-size: 28px; opacity: .72; }
    @keyframes grow { from { transform: scaleX(.08); } to { transform: scaleX(1); } }
  </style>
</head>
<body>
  <main class="frame">
    <div class="eyebrow">Website to video</div>
    <h1>${safeTitle}</h1>
    <p>${safeDescription}</p>
    <div class="bar"></div>
    <div class="source">${safeUrl}</div>
  </main>
</body>
</html>`;
}

function compact(value: string, max: number): string {
  const normalized = value.replace(/\s+/g, " ").trim();
  return normalized.length > max ? `${normalized.slice(0, Math.max(0, max - 1))}…` : normalized;
}

function hostnameTitle(url: string): string {
  return new URL(url).hostname.replace(/^www\./, "");
}

function clampDuration(value?: number): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return 8;
  return Math.max(3, Math.min(30, value));
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
